# values.yaml
grafana:
  enabled: true
  adminPassword: "admin"        
  service:
    type: ClusterIP             
  ingress:
    enabled: false

prometheus:
  service:
    type: ClusterIP              
  ingress:
    enabled: false

alertmanager:
  service:
    type: ClusterIP              
  ingress:
    enabled: false

# Optional persistence (uncomment and ensure a StorageClass exists)
# prometheus:
#   prometheusSpec:
#     storageSpec:
#       volumeClaimTemplate:
#         spec:
#           accessModes: ["ReadWriteOnce"]
#           resources:
#             requests:
#               storage: 20Gi
# grafana:
#   persistence:
#     enabled: true
#     size: 5Gi
# alertmanager:
#   alertmanagerSpec:
#     storage:
#       volumeClaimTemplate:
#         spec:
#           accessModes: ["ReadWriteOnce"]
#           resources:
#             requests:
#               storage: 2Gi
