pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
    }
    
    environment {
        DOCKER_REGISTRY = 'axsoftware/boot-chart'
        GITHUB_REPO = 'https://github.com/andreixmartins/boot-chart.git'
    }
    
    stages {
         stage('Checkout') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: '*/main']],
                        userRemoteConfigs: [[url: env.GITHUB_REPO]]]
                    )
                }
            }
        }

        stage('Build') {
            steps {
                sh 'mvn -B clean install -DskipTests'
            }
        }
        
        stage('Test') {
            steps {
                sh 'mvn test'
            }
        }

        stage('Publish image') {
          steps {
            withCredentials([usernamePassword(credentialsId: 'dockerhub-credential', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
              sh '''
                set -eux
                # Use the SAME storage root/runroot as the build
                POD="podman --storage-driver vfs --root .podman-vfs/root --runroot .podman-vfs/runroot"
                
                $POD build -t "$DOCKER_REGISTRY":"$BUILD_NUMBER" .
                
                # Tag image
                $POD tag localhost/axsoftware/boot-chart:"$BUILD_NUMBER" docker.io/axsoftware/boot-chart:"$BUILD_NUMBER"
        
                # Push image
                $POD login -u "$DOCKER_USER" -p "$DOCKER_PASS" docker.io
                $POD push docker.io/axsoftware/boot-chart:"$BUILD_NUMBER"
              '''
            }
          }
        }        

        stage('Deploy app') {
            steps {
                sh "helm repo add ax https://andreixmartins.github.io/helm-charts"
                sh "helm repo update"
                sh "helm upgrade --install boot-chart ax/boot-chart -n app"
            }
        }
    }
}